### ISSUE TITLE
Can not checkin IFC file

### ISSUE THREAD

**Issue by gujia1088** [opensourceBIM/bimvie.ws#124]
Description
1.I download BIMserver 1.5.125.jar, and installed all recommended plugins.
2.In the checkin page, after select a IFC file, the "Check new revision" does not show, and no deserializer can be selected.
3.In the bulk checkin page, I check in a IFC file successfully, but can not see the 3D view.
Screenshots:
![bulkcheckin](https://user-images.githubusercontent.com/18138674/52771912-2663f200-3072-11e9-8ea5-87108399e1a5.jpg)
![checkin-nodeserializer](https://user-images.githubusercontent.com/18138674/52771917-282db580-3072-11e9-87a4-1808cbb7d97a.jpg)

**Comment by gujia1088** [comment]
Forget to say that I installed "bimviews-0.0.141.jar" from "https://oss.sonatype.org/content/groups/public/org/opensourcebim/bimviews/".

**Comment by rubendel** [comment]
Looks like IfcPlugins is missing. Bulk checkin is only for uploading ZIP files containing multiple IFC files.

**Comment by gujia1088** [comment]
After replace IfcPlugins with the newest version, I checkin a IFC file successfully. But I can not see the 3D of the file. I can not find where is the problem.

**Comment by gujia1088** [comment]
Version of Bimserver is 1.5.125, the picture is all plugins version I used.  Maybe some of the version is incompatible.
![allplugins](https://user-images.githubusercontent.com/18138674/52986811-d8653a80-3433-11e9-9953-0f4fa58a6226.png)

**Comment by bimmodel** [comment]
I also can not load the model there is no button "check" it appears when I try to download the file and the URL [https://github.com/openBIMstandards/DataSetSchependomlaan/raw/master/Design%20model%20IFC/IFC%20Schependomlaan.ifc](https://github.com/openBIMstandards/DataSetSchependomlaan/raw/master/Design%20model%20IFC/IFC%20Schependomlaan.ifc), but when you click, too, or what does not happen, I realized it because of the plugins below I give the log from the eclipse console


```
-plugins "C:\Users\Администратор\git\bimvie.ws" 
-plugins "C:\Users\Администратор\git\BIMsurfer" 
-plugins "C:\Users\Администратор\git\BIMserver-JavaScript-API"
-plugins "C:\Users\Администратор\git\Console\Console"
-plugins "C:\Users\Администратор\git\IfcPlugins\IfcPlugins"
```
console log
```
Logging to C:\Users\Администратор\git\BIMserver\BimServerJar\tmptestdata\home\logs\bimserver.log
14:18:29 INFO  [main]: Starting BIMserver (Windows 7, 1.8.0_211, 64bit, Xmx: 3,87 GB)                   (BimServer.java:244) 
14:18:36 INFO  [main]: Version: 1.5.138-SNAPSHOT                                                        (BimServer.java:332) 
14:18:36 INFO  [main]: Using "tmptestdata\home" as homedir                                              (BimServer.java:341) 
14:18:48 INFO  [main]: Non-empty database directory found "tmptestdata\home\database"                   (BerkeleyKeyValueStore.java:85) 
14:18:51 INFO  [main]: Checking for stale records, this can take some time...                           (BimServer.java:809) 
14:18:51 INFO  [main]: Done checking for stale records (47 ms)                                          (BimServer.java:839) 
14:18:52 INFO  [main]: Changing server state to RUNNING                                                 (ServerInfoManager.java:114) 
14:18:52 INFO  [main]: Initializing database dependant logic...                                         (BimServer.java:1105) 
14:18:52 INFO  [main]: Done initializing database dependant logic (50ms)                                (BimServer.java:1256) 
14:19:11 INFO  [main]: Loading plugins...                                                               (AbstractLocalDevBimServerStarter.java:91) 
14:19:13 INFO  [main]: All plugins loaded (2439 ms)                                                     (AbstractLocalDevBimServerStarter.java:95) 
14:19:13 ERROR [main]:                                                                                  (LocalDevPluginLoader.java:40) 
org.bimserver.shared.exceptions.PluginException: java.lang.Error: Unresolved compilation problems: 
	The import org.bimserver.emf cannot be resolved
	The import org.bimserver.models cannot be resolved
	The import org.bimserver.plugins cannot be resolved
	The import org.bimserver.plugins cannot be resolved
	The import org.bimserver.plugins cannot be resolved
	The import org.bimserver.plugins cannot be resolved
	The import org.bimserver.shared cannot be resolved
	AbstractSerializerPlugin cannot be resolved to a type
	EmfSerializer cannot be resolved to a type
	PluginConfiguration cannot be resolved to a type
	PluginContext cannot be resolved to a type
	PluginConfiguration cannot be resolved to a type
	PluginException cannot be resolved to a type
	The method getDefaultContentType() of type JsonSerializerPlugin must override or implement a supertype method
	The method getDefaultExtension() of type JsonSerializerPlugin must override or implement a supertype method
	ObjectDefinition cannot be resolved to a type
	The method getUserSettingsDefinition() of type JsonSerializerPlugin must override or implement a supertype method
	AbstractSerializerPlugin cannot be resolved to a type
	Schema cannot be resolved to a type
	The method getSupportedSchemas() of type JsonSerializerPlugin must override or implement a supertype method
	Schema cannot be resolved
	Schema cannot be resolved to a variable
	Schema cannot be resolved to a variable
	Schema cannot be resolved to a type
	IFC2X3TC1 cannot be resolved to a variable
	IFC4 cannot be resolved to a variable

	at org.bimserver.plugins.PluginBundleManager.loadPlugins(PluginBundleManager.java:309)
	at org.bimserver.plugins.PluginBundleManager.loadJavaProject(PluginBundleManager.java:447)
	at org.bimserver.plugins.PluginBundleManager.loadPluginsFromEclipseProject(PluginBundleManager.java:480)
	at org.bimserver.LocalDevPluginLoader.loadPlugins(LocalDevPluginLoader.java:38)
	at org.bimserver.AbstractLocalDevBimServerStarter.start(AbstractLocalDevBimServerStarter.java:92)
	at org.bimserver.LocalDevBimServerStarter.main(LocalDevBimServerStarter.java:37)
Caused by: java.lang.Error: Unresolved compilation problems: 
	The import org.bimserver.emf cannot be resolved
	The import org.bimserver.models cannot be resolved
	The import org.bimserver.plugins cannot be resolved
	The import org.bimserver.plugins cannot be resolved
	The import org.bimserver.plugins cannot be resolved
	The import org.bimserver.plugins cannot be resolved
	The import org.bimserver.shared cannot be resolved
	AbstractSerializerPlugin cannot be resolved to a type
	EmfSerializer cannot be resolved to a type
	PluginConfiguration cannot be resolved to a type
	PluginContext cannot be resolved to a type
	PluginConfiguration cannot be resolved to a type
	PluginException cannot be resolved to a type
	The method getDefaultContentType() of type JsonSerializerPlugin must override or implement a supertype method
	The method getDefaultExtension() of type JsonSerializerPlugin must override or implement a supertype method
	ObjectDefinition cannot be resolved to a type
	The method getUserSettingsDefinition() of type JsonSerializerPlugin must override or implement a supertype method
	AbstractSerializerPlugin cannot be resolved to a type
	Schema cannot be resolved to a type
	The method getSupportedSchemas() of type JsonSerializerPlugin must override or implement a supertype method
	Schema cannot be resolved
	Schema cannot be resolved to a variable
	Schema cannot be resolved to a variable
	Schema cannot be resolved to a type
	IFC2X3TC1 cannot be resolved to a variable
	IFC4 cannot be resolved to a variable

	at org.bimserver.serializers.JsonSerializerPlugin.<init>(JsonSerializerPlugin.java:22)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	at org.bimserver.plugins.PluginBundleManager.loadPlugins(PluginBundleManager.java:294)
	... 5 common frames omitted
```

**Comment by bimmodel** [comment]
I solved my problem by reinstalling all the plugins from the bimview page: 
I went to the page 
[http://localhost:8080/apps/bimviews/?page=ServerSettings&subpage=InstalledPluginBundles](http://localhost:8080/apps/bimviews/?page=ServerSettings&subpage=InstalledPluginBundles)
and downgrade all plugins from the current version to the latest version for example
**BIMvie.ws 0.0.148 instaled ->BIMvie.ws 0.0.147 latest ->Update**

just despite the fact that I have in the configuration of eclipse registered 
`-plugins "C:\Users\Администратор\git\IfcPlugins\IfcPlugins"`
 I did not find in the list of installed plug-ins : IfcPlugins. 
Went to the page [http://localhost:8080/apps/bimviews/?page=ServerSettings&subpage=AvailablePluginBundles](http://localhost:8080/apps/bimviews/?page=ServerSettings&subpage=AvailablePluginBundles) and installed it and the rest of the available plugins
