### ISSUE TITLE
No Deserializer option is avilable when checking-in a file to a project

### ISSUE THREAD

**Issue by guysoft** [opensourceBIM/bimvie.ws#43]
Hey,
I have created a new project and want to upload an IFC file to it, however in the Deserializer dropbox menu I only see "Select a Deserializer".
Tried selecting both ifc4 and ics2x3tc.
![checkin_bug](https://cloud.githubusercontent.com/assets/325670/6867954/1f3694ae-d498-11e4-9738-c2dc598e0e39.png)
I have IfcXmlDeserializerPlugin and IfcStepDeserializerPlugin enabled in the admin panel. 

Using a fresh install from yesterday of BIMServer and bimvie.ws latest release (bimviews-1.3.11-FINAL-2015-01-17.jar).
On Firefox latest.

**Comment by guysoft** [comment]
Also does this in Chrome.
When submitting I get: For input string: "null"
Does anyone know anything about this?

**Comment by guysoft** [comment]
Also tried force-setting with the element inspector the value to "IfcStepDeserializer"
But i get back: For input string: "IfcStepDeserializer".

What should I set it to?

**Comment by rubendel** [comment]
Which version of BIMserver?

**Comment by guysoft** [comment]
BIMserver
Current version	1.3.2
Current version date	21-08-2014
Schema version	12

**Comment by rubendel** [comment]
That's the problem. Use a newer version of BIMserver, or use a BIMvie.ws version from around the same date.

**Comment by guysoft** [comment]
Ok flushed ``/var/bimserver/home``  and installed:

BIMServer 1.4.0 14-03-2015
Schema version	14
This is the last RC known to date.

 and BIMviews ``bimviews-1.3.11-FINAL-2015-01-17.jar``

Admin panel loads fine, but BIMviews hangs on ``Loading BIMviews...`` , the only error I can see is in ``/var/bimserver/home/logs/bimserver.log``:

    29-03-2015 17:01:45 ERROR                                                                                  (org.bimserver.servlets.RootServlet.java:141) 
    java.lang.AbstractMethodError
            at org.bimserver.plugins.web.AbstractWebModulePlugin.service(AbstractWebModulePlugin.java:93)
            at org.bimserver.servlets.RootServlet.service(RootServlet.java:121)
            at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
            at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
            at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
            at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
            at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
            at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
            at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
            at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
            at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
            at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
            at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
            at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
            at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
            at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
            at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
            at java.lang.Thread.run(Thread.java:745)

Can you please list two versions of BIMServer and BIMviews that are known to work?

Suggestion: If they are that highly dependant it might be a good idea to check the version and display a warning if they don't match known criteria.

**Comment by guysoft** [comment]
AH, Just saw that the latest version of BIMServer comes with BIMviews pre-installed, which obvioiusly matches it. So closing. Thanks for the help!
