### ISSUE TITLE
BIM viewer often doesn't show the model (Java error> Streamer: IllegalStateException TEXT_FULL_WRITING)

### ISSUE THREAD

**Issue by mansch** [opensourceBIM/bimvie.ws#73]
With the changes regarding the update of the JS api (e.g. rename of queryNew -> query) there seem to be some side effects. Nearly everytime bimvie.ws is not able to display the 3D model. It gets stuck at this state:
![stuck](https://cloud.githubusercontent.com/assets/19776754/20264641/dfd6ca16-aa6c-11e6-8822-37a9893b46f0.png)

Seems to be affected by timing. Reloading the page several times it sometims works, but reloading again may fail again.

Release 1.6.61 with latest plugins:
BIMServer JavaScript API	0.0.103
BIMsurfer	0.0.30
BIMvie.ws	0.0.66

**Comment by mansch** [comment]
For larger models BIMvie.ws sometimes at least starts loading but then stops. Some parts of the model are already painted, then no more updates happen, both stuck (progressbar and scene).

![stuck2](https://cloud.githubusercontent.com/assets/19776754/20302292/f17da4dc-ab26-11e6-91be-bf682ef314d0.png)

Tomcat output shows the error:
11:28:13 INFO  [org.bimserver.ServiceInterface.download]: Reading from cache ea44a421324c667ee2d5becd4a81fa26                              (
NewDiskCacheManager.java:105)
5 ms prepare time
11:28:14 ERROR [Streamer 287]:                                                                                  (BimServer.java:205)
java.lang.IllegalStateException: The remote endpoint was in state [TEXT_FULL_WRITING] which is an invalid state for called method
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase$StateMachine.checkState(WsRemoteEndpointImplBase.java:1177) ~[tomcat-websock
et.jar:8.0.33]
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase$StateMachine.binaryStart(WsRemoteEndpointImplBase.java:1130) ~[tomcat-websoc
ket.jar:8.0.33]
        at org.apache.tomcat.websocket.WsRemoteEndpointImplBase.sendBytes(WsRemoteEndpointImplBase.java:133) ~[tomcat-websocket.jar:8.0.33]
        at org.apache.tomcat.websocket.WsRemoteEndpointBasic.sendBinary(WsRemoteEndpointBasic.java:43) ~[tomcat-websocket.jar:8.0.33]
        at org.bimserver.servlets.websockets.jsr356.Jsr356Impl.sendBlocking(Jsr356Impl.java:133) ~[bimserver-1.5.61.jar:na]
        at org.bimserver.servlets.Streamer$1.run(Streamer.java:100) ~[bimserver-1.5.61.jar:na]

**Comment by rubendel** [comment]
Pretty sure this is fixed in https://github.com/opensourceBIM/BIMserver/commit/ca2bb52c121237a9fa8f693083d0999eae7856f4. I'll make a new release with this fix in it this week.

**Comment by mansch** [comment]
Thanks! :+1: I've tested 1.5.62-SNAPSHOT and can confirm its working there.. like a charm :)

**Comment by rubendel** [comment]
Cool, thanks for confirming
